spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video_web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: liujie
    password: Qq961801961.
    # tomcat服务器是有数据传输大小的
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: video-web
server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

minio:
  endpoint: http://localhost:9000 #MinIO服务所在地址
  bucketName: video #存储桶名称
  accessKey: AKIAIOSFODNN7EXAMPLE #访问的key
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY #访问的秘钥

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

viewCount:
  modifiedQueue: modifiedQueue