spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video_web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: liujie
    password: Qq961801961.
server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
